//所有数据栏目
var category = {
	"home":{
		"id":0,
		"name":"首页",
		"category":{
			"mydata":{
				"id":0,
				"name":"我的数据",
				"url":"more",
				"category":{
					"0":{
						"code":"home_mydata@add",
						"sizex":1,
						"sizey":3,
						"name":"增加关注数据"
					},
					"1":{
						"code":"stock_stock_a_top@stock_a_top",
						"sizex":1,
						"sizey":6,
						"sort":"changepercent^0",
						"cate":"stock",
						"name":"A股涨跌排行榜",
						"hq":["","","",3,"signFormat(s[3]==0?'0.00':((s[3]-s[2])*100/s[2]).toFixed(2))",""]
					},
					"2":{
						"id":2,
						"code":"stock_stock_h_top@stock_h_top",
						"sizex":1,
						"sizey":6,
						"sort":"changepercent^0",
						"cate":"stock",
						"name":"H股涨跌排行榜",
						"hq":["hk","","","parseFloat(s[6]).toFixed(2)","signFormat(parseFloat(s[8]).toFixed(2))",""]
					},
					"3":{
						"code":"stock_stock_us_top@stock_us_top",
						"sizex":1,
						"sizey":6,
						"sort":"chg^0",
						"cate":"stock",
						"name":"美股涨跌排行榜",
						"hq":["gb_","","",1,"signFormat(s[2])",""]
					},
					"4":{
						"code":"futures_futures_top@futures_top",
						"sizex":1,
						"sizey":6,
						"sort":"zdf^0^0",
						"cate":"futures",
						"name":"国内期货主力合约排行"
					},
					"5":{
						"code":"fund_hlwlcjjb@hlwlcjjb",
						"sizex":1,
						"sizey":6,
						"sort":"qrnh^0^0",
						"cate":"fund",
						"name":"互联网理财排行榜"
					},
					"6":{
						"code":"bond_zqhq_gsz@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"yield^0",
						"cate":"other",
						"name":"公司债收益率排行"
					},
					"7":{
						"code":"stock_rdzz_scbx_ltsz@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"nmc^0",
						"cate":"stock",
						"name":"股票流通市值排行"
					},
					"8":{
						"code":"stock_rdzz_scbx_jdgd@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"_5high^0",
						"cate":"stock",
						"name":"A股阶段最高最低"
					},
					"9":{
						"code":"stock_rdzz_scbx_dqzd@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"_2changes^0",
						"cate":"stock",
						"name":"A股短期涨跌统计"
					},
					"10":{
						"code":"stock_rdzz_scbx_cqzd@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"_10changes^0",
						"cate":"stock",
						"name":"A股长期涨跌统计"
					},
					"11":{
						"code":"stock_rdzz_scbx_30xg@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"close^0",
						"cate":"stock",
						"name":"A股创新高个股"
					},
					"12":{
						"code":"stock_rdzz_scbx_30xd@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"close^1",
						"cate":"stock",
						"name":"A股创新低个股"
					},
					"13":{
						"code":"stock_rdzz_scbx_cjzz@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"changes_volume_per^0",
						"cate":"stock",
						"name":"A股成交骤增个股"
					},
					"14":{
						"code":"stock_rdzz_scbx_cjzj@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"changes_volume_per^1",
						"cate":"stock",
						"name":"A股成交骤减个股"
					},
					"15":{
						"code":"stock_rdzz_scbx_lxfl@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"A股连续放量个股"
					},
					"16":{
						"code":"stock_rdzz_scbx_lxsl@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"A股连续缩量个股"
					},
					"17":{
						"code":"stock_rdzz_scbx_lxsz@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"A股连续上涨个股"
					},
					"18":{
						"code":"stock_rdzz_scbx_lxxd@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"A股连续下跌个股"
					},
					"19":{
						"code":"stock_tzgj_zjfw@zjfw",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"最近访问"
					},
					"20":{
						"code":"stock_zixuan@zx",
						"sizex":1,
						"sizey":6,
						"sort":"day_con^0",
						"cate":"stock",
						"name":"我的自选股"
					},
					"21":{
						"code":"stock_schq_mggs_zggng@block_1",
						"sizex":1,
						"sizey":6,
						"sort":"chg^0",
						"cate":"stock",
						"name":"中国概念股（美股）"
					}
				}
			}
		}
	},
	"visual":{
		"id":1,
		"name":"可视化与大数据",
		"category":{
			"hqgszz":{
				"id":0,
				"name":"环球股市指数"
			},
			"agssdd":{
				"id":1,
				"name":"A股实时大单"
			},
			"agrt":{
				"id":2,
				"name":"A股热图"
			},
			"qhrt":{
				"id":3,
				"name":"期货热图"
			},
			"wbyq":{
				"id":4,
				"name":"微博舆情倾听"
			},
			"gnzz":{
				"id":5,
				"name":"市场热点追踪"
			}
		}
	},
	"global":{
		"id":2,
		"name":"环球市场",
		"category":{
			"hqgs":{
				"id":0,
				"name":"环球股市",
				"link":"#visual-hqgszz"
			},
			"hqsp":{
				"id":1,
				"name":"环球商品",
				"url":"http://finance.sina.com.cn/money/globalindex/hf.shtml"
			},
			"yhcjlv":{
				"id":2,
				"name":"银行拆借利率",
				"url":"http://finance.sina.com.cn/money/globalindex/ibor.shtml"
			},
			"zygjgzsyl":{
				"id":3,
				"name":"主要国家国债收益率",
				"url":"http://finance.sina.com.cn/money/forex/hq/GZSYL.shtml"
			},
			"7x24":{
				"id":4,
				"name":"7*24环球财经直播",
				"url":"http://live.sina.com.cn/zt/f/v/finance/globalnews1"
			}
		}
	},
	"stock":{
		"id":3,
		"name":"股票",
		"category":{
			"schq":{
				"id":0,
				"name":"市场行情",
				"category":{
					"hsgs":{
						"id":0,
						"name":"沪深股市",
						"category":{
							"qbag":{
								"id":0,
								"name":"全部A股"
							},
							"zxqy":{
								"id":1,
								"name":"中小企业"
							},
							"cyb":{
								"id":2,
								"name":"创业板"
							},
							"xlhy":{
								"id":3,
								"name":"新浪行业板块",
								"sep":1
							},
							"gnbk":{
								"id":4,
								"name":"概念板块"
							},
							"dybk":{
								"id":5,
								"name":"地域板块"
							},
							"zs":{
								"id":6,
								"name":"指数",
								"sep":1
							},
							"zscf":{
								"id":7,
								"name":"指数成分：",
								"sep":1,
								"disable":1
							},
							"szzz":{
								"id":8,
								"name":"上证指数"
							},
							"szcz":{
								"id":9,
								"name":"深证成指"
							},
							"hs300":{
								"id":10,
								"name":"沪深300"
							}
						}
					},
					"hgt":{
						"id":1,
						"name":"沪港通",
						"disable":1
					},
					"cwsc":{
						"id":2,
						"name":"场外市场",
						"url":"http://otc.finance.sina.com.cn/market/index/CSF.htm"
					},
					"xggs":{
						"id":3,
						"name":"香港股市",
						"category":{
							"qbgg":{
								"id":0,
								"name":"全部港股"
							},
							"lcg":{
								"id":1,
								"name":"蓝筹股"
							},
							"hcg":{
								"id":2,
								"name":"红筹股"
							},
							"gqg":{
								"id":3,
								"name":"国企股"
							},
							"cyb":{
								"id":4,
								"name":"创业板"
							},
							"zs":{
								"id":5,
								"name":"指数"
							}
						}
					},
					"mggs":{
						"id":4,
						"name":"美国股市",
						"category":{
							"qbmg":{
								"id":0,
								"name":"全部美股"
							},
							"zmmg":{
								"id":1,
								"name":"知名美股"
							},
							"zggng":{
								"id":2,
								"name":"中国概念股"
							},
							"zscf":{
								"id":3,
								"name":"指数成分：",
								"sep":1,
								"disable":1
							},
							"dqs":{
								"id":4,
								"name":"道琼斯"
							},
							"nsdk":{
								"id":5,
								"name":"纳斯达克"
							},
							"bp500":{
								"id":6,
								"name":"标普500"
							}
						}
					},
					"qqgszs":{
						"id":5,
						"name":"全球股市指数",
						"link":"#visual-hqgszz"
					}
				}
			},
			"rdzz":{
				"id":1,
				"name":"热点追踪",
				"category":{
					"scbx":{
						"id":0,
						"name":"市场表现",
						"category":{
							"jdgd":{
								"id":0,
								"name":"阶段最高最低"
							},
							"dqzd":{
								"id":1,
								"name":"短期涨跌统计"
							},
							"cqzd":{
								"id":2,
								"name":"长期涨跌统计"
							},
							"30xg":{
								"id":3,
								"name":"盘中创新高个股"
							},
							"30xd":{
								"id":4,
								"name":"盘中创新低个股"
							},
							"cjzz":{
								"id":5,
								"name":"成交骤增个股"
							},
							"cjzj":{
								"id":6,
								"name":"成交骤减个股"
							},
							"lxfl":{
								"id":7,
								"name":"连续放量个股"
							},
							"lxsl":{
								"id":8,
								"name":"连续缩量个股"
							},
							"lxsz":{
								"id":9,
								"name":"连续上涨个股"
							},
							"lxxd":{
								"id":10,
								"name":"连续下跌个股"
							},
							"zzd":{
								"id":11,
								"name":"周涨跌排名"
							},
							"yzqs":{
								"id":12,
								"name":"一周强势股"
							},
							"yzd":{
								"id":13,
								"name":"月涨跌排名"
							},
							"yyqs":{
								"id":14,
								"name":"一月强势股"
							},
							"ltsz":{
								"id":15,
								"name":"流通市值排行"
							},
							"sylv":{
								"id":16,
								"name":"市盈率排行"
							},
							"sjlv":{
								"id":17,
								"name":"市净率排行"
							}
						}
					},
					"zjlx":{
						"id":1,
						"name":"资金流向",
						"url":"http://money.finance.sina.com.cn/moneyflow"
					},
					"rzrq":{
						"id":2,
						"name":"融资融券"
					},
					"dzjy":{
						"id":3,
						"name":"大宗交易"
					},
					"jgcg":{
						"id":4,
						"name":"机构持股",
						"category":{
							"jgcg":{
								"id":0,
								"name":"机构持股汇总"
							},
							"jjzc":{
								"id":1,
								"name":"基金重仓股"
							},
							"sbzc":{
								"id":2,
								"name":"社保重仓股"
							},
							"qfii":{
								"id":3,
								"name":"QFII重仓股"
							}
						}
					},
					"zllhb":{
						"id":5,
						"name":"主力龙虎榜",
						"category":{
							"lhb":{
								"id":0,
								"name":"每日详情"
							},
							"ggtj":{
								"id":1,
								"name":"个股上榜统计"
							},
							"yytj":{
								"id":2,
								"name":"营业部上榜统计"
							},
							"jgzz":{
								"id":3,
								"name":"机构席位追踪"
							},
							"jgmx":{
								"id":4,
								"name":"机构席位成交明细"
							}
						}
					},
					"ggzjc":{
						"id":6,
						"name":"高管增减持"
					},
					"xsjj":{
						"id":7,
						"name":"限售解禁"
					}
				}
			},
			"yjfx":{
				"id":2,
				"name":"研究分析",
				"category":{
					"nbjb":{
						"id":0,
						"name":"年报季报",
						"category":{
							"ylnl":{
								"id":0,
								"name":"盈利能力"
							},
							"yynl":{
								"id":1,
								"name":"营运能力"
							},
							"cnl":{
								"id":2,
								"name":"成长能力"
							},
							"cznl":{
								"id":3,
								"name":"偿债能力"
							},
							"xjll":{
								"id":4,
								"name":"现金流量"
							},
							"yjbb":{
								"id":5,
								"name":"业绩报表"
							},
							"yjyg":{
								"id":6,
								"name":"业绩预告"
							},
							"yjkb":{
								"id":7,
								"name":"业绩快报"
							},
							"lrxf":{
								"id":8,
								"name":"利润细分"
							}
						}
					},
					"qsyb":{
						"id":1,
						"name":"券商研报"
					},
					"qgqp":{
						"id":2,
						"name":"千股千评"
					},
					"lsfh":{
						"id":3,
						"name":"历史分红"
					},
					"ggzd":{
						"id":4,
						"name":"个股诊断",
						"url":"http://finance.sina.com.cn/stock/message/gxq/sh600000/ggzd.html"
					},
					"jgc":{
						"id":5,
						"name":"机构荐股池",
						"category":{
							"zxpj":{
								"id":0,
								"name":"最新投资评级"
							},
							"stpj":{
								"id":1,
								"name":"上调评级股票"
							},
							"xtpj":{
								"id":2,
								"name":"下调评级股票"
							},
							"zhpj":{
								"id":3,
								"name":"股票综合评级"
							},
							"scpj":{
								"id":4,
								"name":"首次评级股票"
							},
							"mbzf":{
								"id":5,
								"name":"目标涨幅排名"
							},
							"jggz":{
								"id":6,
								"name":"机构关注度"
							},
							"hygz":{
								"id":7,
								"name":"行业关注度"
							},
							"gjyc":{
								"id":8,
								"name":"主流股价预测"
							}
						}
					},
					"pjxg":{
						"id":6,
						"name":"投资评级选股",
						"url":"http://vip.stock.finance.sina.com.cn/q/go.php/vIR_CustomSearch/index.phtml"
					}
				}
			},
			"tzgj":{
				"id":3,
				"name":"投资工具",
				"category":{
					"tjxg":{
						"id":0,
						"name":"条件选股",
						"url":"http://screener.finance.sina.com.cn/?from=database"
					},
					"bjgj":{
						"id":1,
						"name":"比较工具",
						"url":"http://biz.finance.sina.com.cn/company/compare/compare.php"
					},
					"tzrl":{
						"id":2,
						"name":"投资日历"
					},
					"jyts":{
						"id":3,
						"name":"交易提示",
						"url":"http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/jyts/index.phtml"
					},
					"gsld":{
						"id":4,
						"name":"股市雷达",
						"url":"http://finance.sina.com.cn/stockradar/index.html"
					},
					"zjfw":{
						"id":5,
						"name":"最近访问"
					}
				}
			},
			"sccyz":{
				"id":4,
				"name":"市场参与者",
				"category":{
					"fxspm":{
						"id":0,
						"name":"分析师排名",
						"category":{
							"zjxg":{
								"id":0,
								"name":"最佳选股分析师"
							},
							"zzyc":{
								"id":1,
								"name":"盈利预测最准分析师"
							},
							"qsph":{
								"id":2,
								"name":"券商研究力量排行"
							}
						}
					},
					"jjjl":{
						"id":1,
						"name":"基金经理",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjjlzz"
					},
					"jjgs":{
						"id":2,
						"name":"基金公司",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjgs"
					}
				}
			}
		}
	},
	"fund":{
		"id":4,
		"name":"基金",
		"category":{
			"jjfl":{
				"id":0,
				"name":"基金行情",
				"category":{
					"fbsjj":{
						"id":0,
						"name":"封闭式基金"
					},
					"etf":{
						"id":1,
						"name":"ETF"
					},
					"lof":{
						"id":2,
						"name":"LOF"
					},
					"fjjj":{
						"id":3,
						"name":"分级基金"
					},
					"hbjjsy":{
						"id":4,
						"name":"货币基金收益"
					},
					"hlwlcjjb":{
						"id":5,
						"name":"互联网理财基金宝",
						"url":"http://finance.sina.com.cn/fund/box"
					}
				}
			},
			"jjph":{
				"id":1,
				"name":"基金排行",
				"category":{
					"xfjj":{
						"id":0,
						"name":"新发基金产品",
						"url":"http://finance.sina.com.cn/fund/fundnew.html"
					},
					"jjph":{
						"id":1,
						"name":"业绩排行",
						"url":"http://money.finance.sina.com.cn/fund_center/#hbphall"
					},
					"jjjz":{
						"id":2,
						"name":"基金净值",
						"url":"http://money.finance.sina.com.cn/fund_center/#jzkfall"
					},
					"jjgm":{
						"id":3,
						"name":"基金规模",
						"url":"http://money.finance.sina.com.cn/fund_center/#jjgmall"
					},
					"jjgz":{
						"id":4,
						"name":"基金估值",
						"url":"http://money.finance.sina.com.cn/fund_center/#pzgz"
					},
					"jjpj":{
						"id":5,
						"name":"基金评级",
						"url":"http://money.finance.sina.com.cn/fund_center/#cxpjgpx"
					},
					"cesy":{
						"id":6,
						"name":"超额收益",
						"url":"http://money.finance.sina.com.cn/fund_center/#cesyzdgpkf"
					},
					"jjfh":{
						"id":7,
						"name":"基金分红",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#fhphall"
					},
					"jjcc":{
						"id":8,
						"name":"基金持仓",
						"url":"http://money.finance.sina.com.cn/fund_center/#jjcczcg"
					}
				}
			},
			"jjgj":{
				"id":2,
				"name":"基金工具",
				"category":{
					"jjbbx":{
						"id":0,
						"name":"基金百宝箱",
						"url":"http://stock2.finance.sina.com.cn/box/view"
					},
					"jjsx":{
						"id":1,
						"name":"基金筛选",
						"url":"http://finance.sina.com.cn/money/fund/filter"
					},
					"jjdtjsq":{
						"id":2,
						"name":"基金定投计算器",
						"url":"http://finance.sina.com.cn/money/fund/dingtou"
					},
					"jjdb":{
						"id":3,
						"name":"基金对比",
						"url":"http://finance.sina.com.cn/money/fund/compare"
					}
				}
			},
			"jjda":{
				"id":3,
				"name":"基金档案",
				"category":{
					"jjjl":{
						"id":4,
						"name":"基金经理",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjjlzz"
					},
					"jjgs":{
						"id":5,
						"name":"基金公司",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#jjgs"
					},
					"dxjg":{
						"id":6,
						"name":"代销机构",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#yh"
					},
					"tgyh":{
						"id":7,
						"name":"托管银行",
						"url":"http://vip.stock.finance.sina.com.cn/fund_center/index.html#tgyh"
					}
				}
			}
		}
	},
	"futures":{
		"id":5,
		"name":"期货",
		"category":{
			"qhhq":{
				"id":0,
				"name":"市场行情",
				"category":{
					"gnqh":{
						"id":0,
						"name":"国内期货"
					},
					"wpqh":{
						"id":1,
						"name":"外盘期货",
						"category":{
							"spqh":{
								"id":0,
								"name":"商品期货"
							},
							"gzqh":{
								"id":1,
								"name":"股指期货"
							},
							"whqh":{
								"id":2,
								"name":"外汇期货"
							}
						}
					},
					"jytd":{
						"id":2,
						"name":"金银T+D"
					}
				}
			},
			"cjccfx":{
				"id":1,
				"name":"成交持仓分析",
				"category":{
					"spcjcc":{
						"id":0,
						"name":"商品成交持仓",
						"url":"http://vip.stock.finance.sina.com.cn/q/view/vFutures_Positions_cjcc.php"
					},
					"gzcjcc":{
						"id":1,
						"name":"股指成交持仓",
						"url":"http://vip.stock.finance.sina.com.cn/q/view/vCffex_Positions_cjcc.php"
					},
					"cftcccbgyy":{
						"id":2,
						"name":"CFTC持仓报告-原油",
						"url":"http://finance.sina.com.cn/futures/quotes/CFCTCL.shtml"
					},
					"cftcccbghj":{
						"id":3,
						"name":"CFTC持仓报告-黄金",
						"url":"http://finance.sina.com.cn/futures/quotes/CFCTGC.shtml"
					},
					"cftcccbgby":{
						"id":4,
						"name":"CFTC持仓报告-白银",
						"url":"http://finance.sina.com.cn/futures/quotes/CFCTSI.shtml"
					}
				}
			},
			"qhgj":{
				"id":2,
				"name":"期货工具",
				"category":{
					"qhhsgjx":{
						"id":0,
						"name":"期货换算工具箱",
						"url":"http://finance.sina.com.cn/money/future/futuretool.html"
					},
					"hs300cfg":{
						"id":1,
						"name":"沪深300成分股权重排行",
						"url":"http://finance.sina.com.cn/qizhi/hs300.html#qz"
					},
					"gzqhtzjsq":{
						"id":2,
						"name":"股指期货投资计算器",
						"url":"http://finance.sina.com.cn/calc/index_futures_pl.html"
					}
				}
			},
			"xhsj":{
				"id":3,
				"name":"现货数据",
				"category":{
					"boce":{
						"id":0,
						"name":"渤海商品"
					},
					"fyme":{
						"id":1,
						"name":"泛亚有色",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_2"
					},
					"lggt":{
						"id":2,
						"name":"兰格钢铁",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_0"
					},
					"fbys":{
						"id":3,
						"name":"富宝有色",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_1"
					},
					"ncpxh":{
						"id":4,
						"name":"农产品现货",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_3"
					},
					"sys":{
						"id":5,
						"name":"生意社",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_4"
					},
					"gzj":{
						"id":6,
						"name":"钢之家",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_5"
					},
					"tks":{
						"id":7,
						"name":"铁矿石",
						"url":"http://finance.sina.com.cn/futuremarket/spotprice.shtml#titlePos_6"
					}
				}
			}
		}
	},
	"forex":{
		"id":6,
		"name":"外汇",
		"category":{
			"whhq":{
				"id":0,
				"name":"外汇行情",
				"category":{
					"jbhl":{
						"id":0,
						"name":"基本汇率"
					},
					"jchl":{
						"id":1,
						"name":"交叉汇率"
					},
					"syhl":{
						"id":2,
						"name":"所有汇率"
					},
					"whqh":{
						"id":3,
						"name":"外汇期货"
					}
				}
			},
			"whsj":{
				"id":1,
				"name":"外汇数据",
				"category":{
					"whpj":{
						"id":0,
						"name":"外汇牌价",
						"url":"http://finance.sina.com.cn/forex/paijia.html#0"
					},
					"pjlszs":{
						"id":1,
						"name":"牌价历史走势",
						"url":"http://biz.finance.sina.com.cn/forex/forex.php"
					},
					"gghgjjsj":{
						"id":2,
						"name":"各国宏观经济数据",
						"url":"http://money.finance.sina.com.cn/forex/view/vDailyFX_Detail.php?country=%C3%C0%B9%FA&event=ISM%D6%C6%D4%EC%D2%B5%D6%B8%CA%FD"
					},
					"qqhgjjsj":{
						"id":3,
						"name":"全球宏观经济数据",
						"url":"http://finance.sina.com.cn/worldmac"
					},
					"cftcccbgmyzs":{
						"id":4,
						"name":"CFTC美元指数持仓报告",
						"url":"http://finance.sina.com.cn/money/forex/hq/CFTCDINIW.shtml"
					},
					"zygjgzsyl":{
						"id":5,
						"name":"主要国家国债收益率",
						"url":"http://finance.sina.com.cn/money/forex/hq/GZSYL.shtml"
					}
				}
			},
			"whgj":{
				"id":2,
				"name":"外汇工具",
				"category":{
					"whrl":{
						"id":0,
						"name":"外汇日历",
						"url":"http://vip.stock.finance.sina.com.cn/forex/view/vDailyFX_More.php"
					},
					"whjsq":{
						"id":1,
						"name":"外汇兑换计算器",
						"url":"http://finance.sina.com.cn/forex/jsq.html"
					}
				}
			}
		}
	},
	"bond":{
		"id":7,
		"name":"债券",
		"category":{
			"zqhq":{
				"id":0,
				"name":"债券行情",
				"category":{
					"kzz":{
						"id":0,
						"name":"可转债"
					},
					"gz":{
						"id":1,
						"name":"国债"
					},
					"gsz":{
						"id":2,
						"name":"公司债"
					},
					"hg":{
						"id":3,
						"name":"回购"
					}
				}
			},
			"zqsj":{
				"id":1,
				"name":"债券数据",
				"category":{
					"zygjgzsyl":{
						"id":0,
						"name":"主要国家债券收益率",
						"url":"http://finance.sina.com.cn/money/forex/hq/GZSYL.shtml"
					}
				}
			}
		}
	},
	"macro":{
		"id":8,
		"name":"经济数据",
		"category":{
			"zghg":{
				"id":0,
				"name":"中国宏观经济数据",
				"url":"http://finance.sina.com.cn/mac"
			},
			"gghg":{
				"id":1,
				"name":"各国宏观经济数据",
				"url":"http://money.finance.sina.com.cn/forex/view/vDailyFX_Detail.php?country=%C3%C0%B9%FA&event=ISM%D6%C6%D4%EC%D2%B5%D6%B8%CA%FD"
			},
			"qqhg":{
				"id":2,
				"name":"全球宏观经济数据",
				"url":"http://finance.sina.com.cn/worldmac"
			}
		}
	},
	"help":{
		"id":99,
		"name":"帮助"
	}
};