var stock_schq_hsgs_plate={
    xlhy_plate:{
        new_blhy:"玻璃行业",
        new_cbzz:"船舶制造",
        new_cmyl:"传媒娱乐",
        new_dlhy:"电力行业",
        new_dqhy:"电器行业",
        new_dzqj:"电子器件",
        new_dzxx:"电子信息",
        new_fdc:"房地产",
        new_fdsb:"发电设备",
        new_fjzz:"飞机制造",
        new_fzhy:"纺织行业",
        new_fzjx:"纺织机械",
        new_fzxl:"服装鞋类",
        new_glql:"公路桥梁",
        new_gsgq:"供水供气",
        new_gthy:"钢铁行业",
        new_hbhy:"环保行业",
        new_hghy:"化工行业",
        new_hxhy:"化纤行业",
        new_dhhy:"家电行业",
        new_jdly:"酒店旅游",
        new_jjhy:"家具行业",
        new_jrhy:"金融行业",
        new_jtys:"交通运输",
        new_jxhy:"机械行业",
        new_jzjc:"建筑建材",
        new_kfq:"开发区",
        new_njhy:"酿酒行业",
        new_mtc:"摩托车",
        new_mthy:"煤炭行业",
        new_nlmy:"农林牧渔",
        new_nyhf:"农药化肥",
        new_qczz:"汽车制造",
        new_qthy:"其它行业",
        new_slzp:"塑料制品",
        new_snhy:"水泥行业",
        new_sphy:"食品行业",
        new_stock:"次新股",
        new_swzy:"生物制药",
        new_sybh:"商业百货",
        new_syhy:"石油行业",
        new_tchy:"陶瓷行业",
        new_wzwm:"物资外贸",
        new_ylqx:"医疗器械",
        new_yqyb:"仪器仪表",
        new_ysbz:"印刷包装",
        new_ysjs:"有色金属",
        new_zhhy:"综合行业",
        new_zzhy:"造纸行业"
    },
    gn_plate:{
        /*gn_yga:"粤港澳",
        gn_gcrj:"国产软件",
        gn_jycx:"基因测序",
        gn_dsgn:"电商概念",
        gn_jyxp:"基因芯片",
        gn_jjj:"京津冀",
        gn_cgl:"草甘膦",
        gn_rldc:"燃料电池",
        gn_qrl:"氢燃料",
        gn_gqgg:"国企改革",
        gn_cdgn:"超导概念",
        gn_znjj:"智能家居",
        gn_lbs:"蓝宝石",
        gn_fn:"风能",
        gn_znjq:"智能机器",
        gn_sygg:"水域改革",
        gn_stny:"生态农业",
        gn_tsl:"特斯拉",
        gn_zjqrgn:"机器人概念",
        gn_tjzm:"天津自贸",
        gn_xxaq:"信息安全",
        gn_yqgg:"油气改革",
        gn_O2Oms:"O2O模式",
        gn_myyy:"民营医院",
        gn_bcgn:"博彩概念",
        gn_ylgn:"养老概念",
        gn_tygn:"体育概念",
        gn_myyh:"民营银行",
        gn_sczl:"丝绸之路",
        gn_ytgn:"婴童概念",
        gn_gdzm:"广东自贸",
        gn_shzm:"上海自贸",
        gn_hljr:"互联金融",
        gn_dyzm:"东亚自贸",
        gn_wlyx:"网络游戏",
        gn_swzn:"生物质能",
        gn_zncd:"智能穿戴",
        gn_qhgn:"前海概念",
        gn_lszm:"绿色照明",
        gn_jaz:"聚氨酯",
        gn_tdlz:"土地流转",
        gn_fszl:"风沙治理",
        gn_smx:"石墨烯",
        gn_4Ggn:"4G概念",
        gn_cdz:"充电桩",
        gn_fngn:"风能概念",
        gn_kqzl:"空气治理",
        gn_znjt:"智能交通",
        gn_jzjn:"建筑节能",
        gn_affw:"安防服务",
        gn_swyz:"生物育种",
        gn_czgn:"重组概念",
        gn_pggn:"苹果概念",
        gn_zmgn:"摘帽概念",
        gn_drn:"地热能",
        gn_nmgh:"内贸规划",
        gn_txw:"碳纤维",
        gn_hsdh:"海水淡化",
        gn_3Ddy:"3D打印",
        gn_swrl:"生物燃料",
        gn_ssgn:"三沙概念",
        gn_tmj:"图们江",
        gn_zSTg:"准ST股",
        gn_yjyj:"业绩预降",
        gn_yjys:"业绩预升",
        gn_szql:"送转潜力",
        gn_scp:"奢侈品",
        gn_gxbj:"高校背景",
        gn_spaq:"食品安全",
        gn_IPV6gn:"IPV6概念",
        gn_kdts:"宽带提速",
        gn_jnhb:"节能环保",
        gn_whzx:"文化振兴",
        gn_swym:"生物疫苗",
        gn_sgn:"陕甘宁",
        gn_zmq:"自贸区",
        gn_rhmy:"日韩贸易",
        gn_yyq:"页岩气",
        gn_jrgg:"金融改革",
        gn_skgn:"涉矿概念",
        gn_bzf:"保障房",
        gn_hgzb:"海工装备",
        gn_xsb:"新三板",
        gn_dzzf:"电子支付",
        gn_yjs:"云计算",*/

        gn_algn:"阿里概念",
        gn_jygn:"基因概念",
        gn_yga:"粤港澳",
        gn_gcrj:"国产软件",
        gn_jycx:"基因测序",
        gn_dsgn:"电商概念",
        gn_jyxp:"基因芯片",
        gn_jjj:"京津冀",
        gn_cgl:"草甘膦",
        gn_rldc:"燃料电池",
        gn_sqrl:"氢燃料",
        gn_sgqgg:"国企改革",
        gn_cdgn:"超导概念",
        gn_znjj:"智能家居",
        gn_lbs:"蓝宝石",
        gn_fn:"风能",
        gn_znjq:"智能机器",
        gn_sygg:"水域改革",
        gn_stny:"生态农业",
        gn_tsl:"特斯拉",
        gn_zjqrgn:"机器人概念",
        gn_mtjzm:"天津自贸",
        gn_xxaq:"信息安全",
        gn_yqgg:"油气改革",
        gn_O2Oms:"O2O模式",
        gn_myyy:"民营医院",
        gn_bcgn:"博彩概念",
        gn_ylgn:"养老概念",
        gn_tygn:"体育概念",
        gn_myyx:"民营银行",
        gn_sczl:"丝绸之路",
        gn_ytgn:"婴童概念",
        gn_gzzm:"广东自贸",
        gn_shzm:"上海自贸",
        gn_hljr:"互联金融",
        gn_dyzm:"东亚自贸",
        gn_wlyx:"网络游戏",
        gn_swzn:"生物质能",
        gn_zncd:"智能穿戴",
        gn_qhgn:"前海概念",
        gn_lszm:"绿色照明",
        gn_jaz:"聚氨酯",
        gn_tdlz:"土地流转",
        gn_fszl:"风沙治理",
        gn_smx:"石墨烯",
        gn_4Ggn:"4G概念",
        gn_cdz:"充电桩",
        gn_fngn:"风能概念",
        gn_kqzl:"空气治理",
        gn_znjt:"智能交通",
        gn_jzjn:"建筑节能",
        gn_affw:"安防服务",
        gn_swyz:"生物育种",
        gn_zzgn:"重组概念",
        gn_pggn:"苹果概念",
        gn_zmgn:"摘帽概念",
        gn_drn:"地热能",
        gn_nmgh:"内贸规划",
        gn_txw:"碳纤维",
        gn_hsdh:"海水淡化",
        gn_3Ddy:"3D打印",
        gn_swrl:"生物燃料",
        gn_ssgn:"三沙概念",
        gn_tmj:"图们江",
        gn_zSTg:"准ST股",
        gn_yjyj:"业绩预降",
        gn_yjys:"业绩预升",
        gn_szql:"送转潜力",
        gn_scp:"奢侈品",
        gn_gxbj:"高校背景",
        gn_spaq:"食品安全",
        gn_IPV6gn:"IPV6概念",
        gn_kdts:"宽带提速",
        gn_jnhb:"节能环保",
        gn_whzx:"文化振兴",
        gn_swym:"生物疫苗",
        gn_sgn:"陕甘宁",
        gn_zmq:"自贸区",
        gn_rhmy:"日韩贸易",
        gn_yyq:"页岩气",
        gn_jrgg:"金融改革",
        gn_skgn:"涉矿概念",
        gn_bzf:"保障房",
        gn_hgzb:"海工装备",
        gn_xsb:"新三板",
        gn_dzzf:"电子支付",
        gn_yjs:"云计算",
        gn_wxdh:"卫星导航",
        gn_tyn:"太阳能",
        gn_wzbj:"外资背景",
        gn_wjqy:"皖江区域",
        gn_czt:"长株潭",
        gn_ztss:"整体上市",
        gn_byjj:"本月解禁",
        gn_sljs:"水利建设",
        gn_cmp:"触摸屏",
        gn_jrcg:"金融参股",
        gn_sbzc:"社保重仓",
        gn_bxzc:"保险重仓",
        gn_xtzc:"信托重仓",
        gn_qszc:"券商重仓",
        gn_QFIIzc:"QFII重仓",
        gn_hdhn:"核电核能",
        gn_xtyc:"稀土永磁",
        gn_ldc:"锂电池",
        gn_djg:"多晶硅",
        gn_jxzs:"精选指数",
        gn_fcss:"分拆上市",
        gn_whgh:"武汉规划",
        gn_cjxj:"超级细菌",
        gn_swrh:"三网融合",
        gn_rzrq:"融资融券",
        gn_xqzy:"稀缺资源",
        gn_hkzz:"含可转债",
        gn_cxg:"次新股",
        gn_hBg:"含B股",
        gn_hHg:"含H股",
        gn_shbd:"上海本地",
        gn_szbd:"深圳本地",
        gn_zxsy:"振兴沈阳",
        gn_yhfz:"沿海发展",
        gn_yq50:"央企50",
        gn_cdp:"超大盘",
        gn_cgjr:"参股金融",
        gn_jjzc:"基金重仓",
        gn_dtjj:"低碳经济",
        gn_gqgn:"股期概念",
        gn_stbk:"ST板块",
        gn_ctgn:"创投概念",
        gn_gqjl:"股权激励",
        gn_jxlg:"甲型流感",
        gn_hjgn:"黄金概念",
        gn_jght:"军工航天",
        gn_wlw:"物联网",
        gn_dsn:"迪士尼",
        gn_ckts:"出口退税",
        gn_tljj:"铁路基建",
        gn_xny:"新能源",
        gn_cytq:"成渝特区",
        gn_hxxa:"海峡西岸",
        gn_hhsj:"黄河三角",
        gn_wgg:"未股改",
        gn_xhjj:"循环经济",
        gn_zndw:"智能电网",
        gn_zczr:"资产注入"
    },
    diyu_plate:{
        diyu_1100:"北京",
        diyu_1200:"天津",
        diyu_1300:"河北",
        diyu_1400:"山西",
        diyu_1500:"内蒙古",
        diyu_2100:"辽宁",
        diyu_2200:"吉林",
        diyu_2300:"黑龙江",
        diyu_3100:"上海",
        diyu_3200:"江苏",
        diyu_3300:"浙江",
        diyu_3400:"安徽",
        diyu_3500:"福建",
        diyu_3600:"江西",
        diyu_3700:"山东",
        diyu_4100:"河南",
        diyu_4200:"湖北",
        diyu_4300:"湖南",
        diyu_4400:"广东",
        diyu_4401:"广州",
        diyu_4410:"深圳",
        diyu_4500:"广西",
        diyu_4600:"海南",
        diyu_5100:"四川",
        diyu_5200:"贵州",
        diyu_5300:"云南",
        diyu_5400:"西藏",
        diyu_5500:"重庆",
        diyu_6100:"陕西",
        diyu_6200:"甘肃",
        diyu_6300:"青海",
        diyu_6400:"宁夏",
        diyu_6500:"新疆"
    }
}


function displayPlateContent(plateId){
    var plateObj;
    var txtName;

    switch(plateId.split("_")[0]){
        case "new":
            txtName="stock_schq_hsgs_xlhy_plate.txt";
            plateObj=stock_schq_hsgs_plate.xlhy_plate;
            break;
        case "gn":
            txtName="stock_schq_hsgs_gnbk_plate.txt";
            plateObj=stock_schq_hsgs_plate.gn_plate;
            break;
        case "diyu":
            txtName="stock_schq_hsgs_dybk_plate.txt";
            plateObj=stock_schq_hsgs_plate.diyu_plate;
            break;
    };


    //ajax请求对应的txt文件
    var theResult=$.ajax({url:"./blocks/"+txtName,async:false});
    //获取请求结果
    var blockJSON=eval('(' + theResult.responseText.replace(/[\r\n]/g,"") + ')');

    //向data_panel中填充html代码
    $("#data_panel").html(blockJSON.html);
    $(".childPlateTitle").text(plateObj[plateId]);

    FDC_DC.blocks=blockJSON.blocks;
    FDC_DC.blocks[0].param=FDC_DC.blocks[0].param.replace("{plateId}",plateId);

    FDC_DC.dealBlocks(0,"");

    for(var i=0; i<FDC_DC.blocks.length;i++){
        //为每页各个显示条数Div添加事件
        $("#numberDiv_"+i).find("a").attr("onclick","FDC_DC.changeNumber(this,"+i+")");

        //为最近几日标签添加事件
        $("#recentDaysDiv_"+i).find("a").attr("onclick","FDC_DC.changeDays(this,"+i+")");

        (function(i){
            var block_field=FDC_DC.blocks[i].field;
            var block_id=FDC_DC.blocks[i].blockId;

            //为表格各个列排序添加事件
            var thList=$("#"+block_id+" thead th");
            for(var j=0; j<thList.length;j++){
                //如果当前th标签里有span标签（这里就要求所有对应表格的字段，都要写成th标签，否则会出错）
                if($(thList[j]).find("span").length!=0){
                    //为含有span标签的th标签绑定事件
                    $(thList[j]).find("span").attr("onclick","FDC_DC.fieldSort(this,"+i+",'"+block_field[j]+"')");
                }
            }

            //为pageDiv里的分页标签们添加事件
            $("#pageDiv_"+i+" input[type=button]").attr("onclick","FDC_DC.gotoPage("+i+")");
            $("#pageDiv_"+i+" .firstPageSpan").attr("onclick","FDC_DC.firstPage("+i+")");
            $("#pageDiv_"+i+" .lastPageSpan").attr("onclick","FDC_DC.lastPage("+i+")");
            $("#pageDiv_"+i+" .previousPageSpan").attr("onclick","FDC_DC.previousPage("+i+")");
            $("#pageDiv_"+i+" .nextPageSpan").attr("onclick","FDC_DC.nextPage("+i+")");


            FDC_DC.dealBlocks(i,"");
        })(i);
    }
}


